DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS events;

CREATE TABLE IF NOT EXISTS users
(
    id    bigint generated by default as identity,
    name  varchar        not null,
    email varchar unique not null,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   bigint generated by default as identity,
    name varchar not null,
    CONSTRAINT categories_pk primary key (id)
);

CREATE table if not exists locations
(
    id  bigint generated by default as identity,
    lat float,
    lon float,
    CONSTRAINT locations_pk primary key (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 bigint generated by default as identity,
    annotation         varchar,
    category_id        bigint references categories (id) not null,
    confirmed_request  integer,
    created_on         timestamp with time zone,
    description        varchar,
    event_date         timestamp with time zone,
    initiator_id       bigint references users (id),
    location_id        bigint references locations (id),
    paid               boolean,
    participantLimit   integer,
    published_on       timestamp with time zone,
    request_moderation boolean,
    state              varchar,
    title              varchar,
    views              integer
);