DROP TABLE IF EXISTS endpoints;

CREATE TABLE IF NOT EXISTS endpoints
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(255)                            NOT NULL,
    uri       VARCHAR(255)                            NOT NULL,
    ip        VARCHAR(16)                             NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_endpoints PRIMARY KEY (id)
);